sudo: required
dist: trusty
language: generic

env:
  global:
    - ROS_DISTRO="indigo"
    - UPSTREAM-WORKSPACE=file
    - ROSINSTALL_FILENAME=.travis.rosinstall

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
